config/routes.rb
Rails.application.routes.draw do
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :services, controller: 'services', only: [:index, :show,:edit, :update, :new, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
require 'swaggers/Account_Management_Service'

class Service < ApplicationRecord
  attr_accessor :service_profile

  after_initialize do
    puts '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ AFTER INITIALISE ###################'
    api_configuration = AccountManagementService::Configuration.new { |config| config.debugging = true }
    api_client = AccountManagementService::ApiClient.new(api_configuration)
    api = AccountManagementService::ServiceProfilesApi.new(api_client)
    @service_profile = api.serviceprofiles_getlocal(ccs_service_id: ccs_service_id).d.results[0]
    @ccs_service_id = ccs_service_id
    @api_dom = @service_profile.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = set_service
    @service_profile = @service.service_profile
    puts @service_profile.to_hash.to_s
  end

  # GET /services/new
  def new
    @service = Service.new(service_params)
    @service.save
    @service_profile = @service.service_profile
    puts @service_profile.to_hash.to_s
  end

  # GET /services/1/edit
  def edit
    @service = set_service
    @service_profile = @service.service_profile
    puts @service_profile.to_hash.to_s
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:ccs_service_id, :api_dom)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hash_format_helper.rb
module HashFormatHelper
  # These methods add classes to the HTML structure that are defined in Bootstrap (and can be defined for other CSS frameworks)
  def format_hash(hash, html = '', read_only = true, form = nil)
    Rails.logger.info "RECEIVED::HASH::#{read_only}: #{hash.to_s}, "

    hash.each do |key, value |
      Rails.logger.info "KEY,VALUE::::: #{key},#{value}"
      #next if value.blank?

      if value.is_a?(String) || value.is_a?(Numeric)  || value.blank?
        html += content_tag(:div, class: 'divTableRow') {
          ul_contents = ''
          ul_contents << content_tag(:div, content_tag(:p, key.to_s.underscore.humanize.titleize),
                                     class: 'divTableCell')
          Rails.logger.info "read only #{read_only}"
          if read_only || (value.is_a?(Hash) && value.empty? )#I'm sure there's a better way to embed the readonly flag...
            ul_contents << content_tag(:input, nil, class:"form-control form-control-sm",
                                     type:"text", name:key,
                                    id:key, value:value,  :readonly => true )
          else
            ul_contents << content_tag(:input, nil, class:"form-control form-control-sm",
                                       type:"text", name:key,
                                       id:key, value:value )
          end
          Rails.logger.info "\n UL_CONTENTS = #{ul_contents}"
          ul_contents.html_safe

        }
      elsif value.is_a?(Hash)
        html += content_tag(:div, class: 'divTableRow') {
          ul_contents = ''
          ul_contents << content_tag(:div, content_tag(:p, key.to_s.underscore.humanize.titleize),
                                     class: 'divTableCell')

          inner = content_tag(:div, format_hash(value, '', read_only), class: 'divTableCell')

          ul_contents << inner

          ul_contents.html_safe
        }
      elsif value.is_a?(Array)
        Rails.logger.info "RECEIVED::ARRAY:: Calling format array"
        html += format_array(value,'', read_only)
      else
        Rails.logger.info "Unexpected value in format_hash: #{value.inspect}"
        Rails.logger.info "value type: #{value.class.name}"
      end
    end
    html.html_safe
  end

  def format_array(array, html = '', read_only)
    Rails.logger.info "RECEIVED::ARRAY::: #{array.to_s}"
    array.each do |value|
      if value.is_a?(String)
        html += content_tag(:div, value).html_safe
      elsif value.is_a?(Hash)
        html += content_tag(:div, class: 'divTableCell') {
          inner = format_hash(value, '', read_only)
          inner.html_safe
        }

      elsif value.is_a?(Array)
        html += format_array(value, html, read_only)
      else
        Rails.logger.info "Unexpected value in format_array: #{value.inspect}"
        Rails.logger.info "value type: #{value.class.name}"
      end
    end
    html
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Velcro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ccs_service_id %>
    <%= form.text_field :ccs_service_id %>
  </div>

  <div class="field">
    <%= form.label :api_dom %>
    <%= form.text_field :api_dom %>
  </div>

  <%= format_hash(@service_profile.to_hash, '') %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_search.html.erb
<div class="table-responsive">
  <div class="divTableBodyWrapper">
    <div class="divTableHeading">
      <div class="divTableRow">

        <div class="divTableCell">
          <h1>Service</h1>
        </div>
        <div class="divTableCell">
        </div>
      </div>

      <%= form_with( url: new_service_path, method: :get, :local => true) do %>
        <div class="divTableRow">
          <div class="divTableCell">
            <div class="divTableHead"><%= label_tag(:ccs_service_id, "Service Id") %>
            </div>
          </div>
          <div class="divTableCell">
            <div class="divTableHead">
              <%= text_field_tag("service[ccs_service_id]") %>
            </div>
          </div>
          <div class="divTableCell"></div>
          <div class="divTableCell"><%= submit_tag("Search") %></div>
        </div>
      <%end %>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Ccs service</th>
      <th>Api dom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.ccs_service_id %></td>
        <td><%= service.api_dom %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= render partial: 'search' %>
<% #= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ccs service:</strong>
  <%= @service.ccs_service_id %>
</p>

<p>
  <strong>Api dom:</strong>
  <%= @service.api_dom %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

<%= format_hash(@service_profile.to_hash, '', @readonly = true) %>